export const SET_IS_AUTHENTICATED_STATE = "SET_IS_AUTHENTICATED_STATE";
export const SET_FULL_NAME = "SET_FULL_NAME";

export const SET_ALERT = "SET_ALERT";
export const CLOSE_ALERT = "CLOSE_ALERT";

export const SET_DESTINATION = "SET_DESTINATION";
export const SET_DATE_RANGE = "SET_DATE_RANGE";
export const SET_NUMBER_OF_GUESTS = "SET_NUMBER_OF_GUESTS";
export const SET_NUMBER_OF_ROOMS = "SET_NUMBER_OF_ROOMS";
export const SET_PRICE_RANGE = "SET_PRICE_RANGE";
export const SET_IS_WIFI_PRESENT = "SET_IS_WIFI_PRESENT";
export const SET_IS_KITCHEN_PRESENT = "SET_IS_KITCHEN_PRESENT";
export const SET_IS_WASHING_MACHINE_PRESENT = "SET_IS_WASHING_MACHINE_PRESENT";
export const SET_SORT_HOTELS = "SET_SORT_HOTELS";

export const SET_DESTINATION_TOOLTIP_OPEN = "SET_DESTINATION_TOOLTIP_OPEN";
export const SET_DATES_TOOLTIP_OPEN = "SET_DATES_TOOLTIP_OPEN";

export const SET_ROOMS_PRICE_RANGE = "SET_ROOMS_PRICE_RANGE";
export const SET_IS_ROOM_KITCHEN_PRESENT = "SET_IS_ROOM_KITCHEN_PRESENT";
export const SET_IS_ROOM_WASHING_MACHINE_PRESENT = "SET_IS_ROOM_WASHING_MACHINE_PRESENT";
export const SET_ROOM_NUMBER_OF_BEDS = "SET_ROOM_NUMBER_OF_GUESTS";
export const SET_ROOM_NUMBER_OF_ROOMS = "SET_ROOM_NUMBER_OF_ROOMS";
export const SET_SORT_ROOMS = "SET_SORT_ROOMS";
