name: Deploy to App Engine

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install & Build
      run: | 
        npm install
        npm run build

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v1.2.7
      with:
        deliverables: app.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"
